# -*- coding: utf-8 -*-
"""ForestPractice.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LGe1tVRZsFTPS9DXAIplCH962ykuvQBV
"""

import numpy as np
import pandas as pd
import time
import datetime
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report,plot_confusion_matrix
from sklearn.metrics import plot_roc_curve
from sklearn.ensemble import RandomForestClassifier
import matplotlib.pyplot as plt
import pandas_datareader as data
from sklearn import metrics
import streamlit as st

def app():
    st.title('Predicción de tendencia de acciones')
    start = '2004-08-18'
    end = '2022-01-20'
    st.title('Predicción de tendencia de acciones')
    user_input = st.text_input('Introducir cotización bursátil' , 'GOOG')
    df = data.DataReader(user_input, 'yahoo', start, end)
    # Seleccion de datos
    df['highest hight'] = df['High'].rolling(window=10).max()
    df['lowest low'] = df['Low'].rolling(window=10).min()
    df['trigger'] = np.where(df['High']==df['highest hight'],1,np.nan)
    df['trigger'] = np.where(df['Low']==df['lowest low'],0,df['trigger'])
    df['position'] = df['trigger'].ffill().fillna(-1) 
    df.drop(df.index[[0,1,2,3,4,5,6,7,8,9]])

    # Eleccion de datos
    df.drop(['Date','Adj Close','Volume','highest hight', 'lowest low', 'trigger'],axis=1)

    # Describiendo los datos
    st.subheader('Datos del 2010 al 2022') 
    st.write(df.describe())

    # Separacion de datos de entrenamiento y prueba
    X = df.drop('position',axis=1)
    y = df['position']
    X_train,X_test, y_train,y_test= train_test_split(X,y,test_size=0.20,random_state=101)

    # Uso del modelo
    modelo = RandomForestClassifier()
    modelo.fit(X_train,y_train)
    st.subheader('Score del modelo') 
    st.write(modelo.score(X_test,y_test))

    # Mejorando el score
    # while True:
    #   modelo = RandomForestClassifier()
    #   modelo.fit(X_train,y_train)
    #   if modelo.score(X_test,y_test)>0.689:
    #     break
    # st.subheader('Nuevo score del modelo') 
    # st.write(modelo.score(X_test,y_test))

    #Visualizaciones 
    pred_modelo = modelo.predict(X_test)
    st.subheader('Classification Report')
    st.write(classification_report(y_test,pred_modelo))
    st.subheader('Confusion Matrix')
    fig = plt.figure(figsize = (12,6))
    plt.plot(plot_confusion_matrix(modelo,X_test,y_test))
    st.pyplot(fig)

    st.subheader('ROC')
    rfc_disp = plot_roc_curve(modelo, X_test, y_test, alpha = 0.8)
    fig = plt.figure(figsize = (12,6))
    plt.plot(rfc_disp)
    st.pyplot(fig)